# Lab 02: Manipulate PyTorch Tensors -- exercise

In [1]:
import torch

### Make the matrices A and B below. Add them together to obtain a matrix C. Print these three matrices.
$$
A =\begin{bmatrix}
1 & 2 \\ 3 & 4
\end{bmatrix}  
\qquad 
B =\begin{bmatrix}
10 & 20 \\ 30 & 40
\end{bmatrix}  \qquad C=A+B =?
$$

In [3]:
# write your code here
a=torch.tensor([[1,2],[3,4]])
b=torch.tensor([[10,20],[30,40]])
c=a+b
print(a)
print(b)
print(c)


tensor([[1, 2],
        [3, 4]])
tensor([[10, 20],
        [30, 40]])
tensor([[11, 22],
        [33, 44]])


### Print the dimension, size and type of the matrix A. Remember, the commands are dim(), size() and type()

In [9]:

# write your code here
print(a.dim(),a.size(),a.type())


2 torch.Size([2, 2]) torch.LongTensor


### Convert the matrix A to be an integer matrix  (type LongTensor). Remember, the command is long(). Then print the type to check it was indeed converted.

In [5]:

# write your code here
aa=a.long()
print(aa.type())


torch.LongTensor


### Make a random 5 x 2 x 3 Tensor. The command is torch.rand.  Then do the following:   1) Print the tensor,  2) Print its type, 3) Print its dimension,  4) Print its size, 5) Print the size of its middle dimension.

In [10]:

# write your code here
rd=torch.rand(5,2,3)
print(rd)
print(rd.type())
print(rd.dim())
print(rd.size())
print(rd.size(1))



tensor([[[0.6573, 0.0270, 0.3934],
         [0.2005, 0.6160, 0.3620]],

        [[0.7676, 0.1291, 0.6618],
         [0.4063, 0.7250, 0.0962]],

        [[0.1315, 0.0882, 0.0096],
         [0.6679, 0.3767, 0.3437]],

        [[0.8174, 0.7370, 0.4060],
         [0.5351, 0.8507, 0.6477]],

        [[0.2020, 0.0144, 0.9407],
         [0.2643, 0.6816, 0.0822]]])
torch.FloatTensor
3
torch.Size([5, 2, 3])
2


### Make 2 x 3 x 4 x 5 tensor filled with zeros then print it. (The command is torch.zeros). See if you can make sense of the display.

In [7]:

# write your code here
zr=torch.zeros(2,3,4,5)
print(zr)


tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]])
