# Lab 01 : Convolutional layer - demo

In [4]:
import torch
import torch.nn as nn

### Make a convolutional module
* inputs:  2 channels
* output:  5 activation maps 
* filters are 3x3
* padding with one layer of zero to not shrink anything

In [5]:
mod = nn.Conv2d( 2 , 5 ,  kernel_size=3,  padding=1 )

### Make an input 2 x 6 x 6  (two channels, each one has 6 x 6 pixels )

In [6]:
bs=1

x=torch.rand(bs,2,6,6)

print(x)

print(x.size())

tensor([[[[0.8396, 0.4119, 0.4831, 0.5742, 0.5526, 0.1545],
          [0.6624, 0.3942, 0.9184, 0.0206, 0.9506, 0.1332],
          [0.1493, 0.4321, 0.3957, 0.6590, 0.5165, 0.1891],
          [0.8336, 0.8860, 0.9261, 0.1794, 0.7926, 0.3232],
          [0.8612, 0.7045, 0.6477, 0.6847, 0.8347, 0.5742],
          [0.1888, 0.2142, 0.4373, 0.2775, 0.3604, 0.6672]],

         [[0.7271, 0.3128, 0.3969, 0.4463, 0.0291, 0.4972],
          [0.7282, 0.0203, 0.3479, 0.7136, 0.9637, 0.7439],
          [0.2755, 0.5171, 0.2943, 0.4752, 0.0745, 0.0627],
          [0.1686, 0.9034, 0.3537, 0.2243, 0.8439, 0.4027],
          [0.6400, 0.4486, 0.9319, 0.1839, 0.0382, 0.0471],
          [0.2001, 0.6022, 0.0892, 0.4949, 0.2157, 0.7014]]]])
torch.Size([1, 2, 6, 6])


### Feed it to the convolutional layer: the output should have 5 channels (each one is 6x6)

In [7]:
y=mod(x)

print(y)

print(y.size())

tensor([[[[-0.0327, -0.2583, -0.1252,  0.0457, -0.1063, -0.1721],
          [ 0.0667, -0.3578, -0.3249, -0.2098, -0.3224, -0.0619],
          [ 0.0651, -0.3333, -0.2428, -0.2490, -0.1110, -0.4118],
          [-0.1144, -0.1839, -0.3417, -0.4109, -0.3628, -0.2796],
          [-0.1888, -0.1717, -0.3460, -0.3520, -0.2106, -0.3991],
          [-0.1640, -0.2982, -0.2653, -0.5089, -0.3278, -0.1691]],

         [[-0.3900,  0.0557, -0.3551, -0.0997, -0.2913,  0.2493],
          [-0.2453, -0.2126, -0.0709, -0.4662, -0.0813,  0.3060],
          [-0.6225, -0.3374, -0.2066,  0.2600, -0.1883,  0.2359],
          [-0.6069, -0.2192,  0.0928, -0.2305, -0.2641,  0.2131],
          [-0.2738, -0.2073, -0.2196,  0.1401, -0.0743, -0.0262],
          [-0.1296,  0.0356,  0.0081, -0.0669, -0.2858,  0.0101]],

         [[-0.0806, -0.0036,  0.1240, -0.1383,  0.4515,  0.1368],
          [-0.0788, -0.0620,  0.1510, -0.1206, -0.0309, -0.1267],
          [ 0.0617, -0.1165,  0.3564,  0.0612,  0.3641,  0.0846],
      

### Lets look at the 5 filters.
* Our filters are 2x3x3
* Each of the filter has 2 channels because the inputs have two channels

In [8]:
print(mod.weight)

print(mod.weight.size())

Parameter containing:
tensor([[[[-0.0143,  0.0093, -0.1948],
          [-0.0979, -0.1393, -0.0133],
          [-0.0661, -0.0869,  0.0643]],

         [[-0.2328,  0.1821,  0.0063],
          [ 0.0593,  0.1667,  0.0089],
          [-0.1093,  0.2182,  0.1344]]],


        [[[-0.0201, -0.2350,  0.1280],
          [ 0.1678,  0.0862, -0.2311],
          [ 0.1389, -0.2134, -0.0978]],

         [[-0.0210,  0.0796,  0.1526],
          [ 0.0976, -0.0366, -0.2353],
          [ 0.1477, -0.1784, -0.1222]]],


        [[[-0.1701, -0.0860,  0.0705],
          [-0.0086,  0.0846, -0.1044],
          [ 0.0435,  0.2113, -0.1911]],

         [[-0.1342,  0.2355,  0.1612],
          [ 0.0645, -0.2203,  0.1048],
          [ 0.2203,  0.0986,  0.0559]]],


        [[[-0.1301, -0.0613, -0.0546],
          [-0.0414,  0.2155, -0.2350],
          [ 0.0011,  0.1017, -0.0642]],

         [[ 0.2028, -0.0422,  0.0915],
          [ 0.0729, -0.2303, -0.1480],
          [-0.0900,  0.1253,  0.0016]]],


        [[[ 0.2201