# Lab 01: Introduction to PyTorch  

In [1]:
import torch

### PyTorch Tensors

### Construct a vector of 3 elements

In [2]:
x=torch.Tensor( [5.3 , 2.1 , -3.1 ] )
print(x)

tensor([ 5.3000,  2.1000, -3.1000])


### Construct a  2 x 2 matrix

In [3]:
A=torch.Tensor( [ [5.3,2.1] , [0.2,2.1] ] )
print(A)

tensor([[5.3000, 2.1000],
        [0.2000, 2.1000]])


### Construct a random 10 x 2 matrix

In [4]:
A=torch.rand(10,2)
print(A)

tensor([[0.3728, 0.1496],
        [0.7327, 0.2834],
        [0.4709, 0.4463],
        [0.6734, 0.1011],
        [0.6415, 0.8119],
        [0.6185, 0.4772],
        [0.6611, 0.6784],
        [0.2657, 0.0891],
        [0.3620, 0.4396],
        [0.8017, 0.2509]])


### Construct a 10 x 2 matrix filled with zeros

In [5]:
A=torch.zeros(10,2)
print(A)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


### Construct a 5 x 2 x 2 random Tensor 

In [6]:
B = torch.rand(5,2,2)
print(B)

tensor([[[0.4578, 0.6779],
         [0.0534, 0.6347]],

        [[0.5078, 0.3202],
         [0.1097, 0.3001]],

        [[0.0336, 0.0319],
         [0.4661, 0.9069]],

        [[0.2142, 0.5108],
         [0.8729, 0.5947]],

        [[0.0413, 0.7309],
         [0.2084, 0.2612]]])


In [7]:
B.size()

torch.Size([5, 2, 2])

In [8]:
B.dim()

3

In [52]:
B.type()

'torch.FloatTensor'

### Size and Dimension of a Tensor 

#### A 3-dimensional Tensor 

In [10]:
A=torch.rand(3,2,2)
print(A)

tensor([[[0.8903, 0.2657],
         [0.5707, 0.2579]],

        [[0.6584, 0.3197],
         [0.3794, 0.8530]],

        [[0.2002, 0.0046],
         [0.9633, 0.8369]]])


In [11]:
print(  A.dim()   )

3


In [12]:
print(  A.size()   )

torch.Size([3, 2, 2])


In [13]:
print(  A.size(0)  )

3


#### A 2-dimensional Tensor 

In [14]:
B=torch.rand(3,5)
print(B)

tensor([[0.7267, 0.6210, 0.4377, 0.7366, 0.0655],
        [0.1710, 0.4525, 0.8202, 0.5162, 0.5639],
        [0.1668, 0.5701, 0.4520, 0.0464, 0.3179]])


In [15]:
print( B.dim()  )

2


In [16]:
print( B.size()  )

torch.Size([3, 5])


In [17]:
print( B.size(0) )

3


In [18]:
print( B.size(1) )

5


#### A 1-dimensional Tensor

In [19]:
x=torch.rand(7)
print(x)

tensor([0.7242, 0.8863, 0.3104, 0.2889, 0.5690, 0.5133, 0.5027])


In [20]:
print( x.dim() )

1


In [21]:
print( x.size() )

torch.Size([7])


### Adding and multiplying tensors

In [50]:
# A=torch.rand(2,2)
# B=torch.rand(2,2)
A = torch.Tensor([[1,2],[3,4]])
B = torch.Tensor([[5,6],[7,8]])
C=2*B
D=A+C
E=A*B
F=A@B
print(A)
print('')
print(B)
print('')
print(C)
print('')
print(D)
print('')
print(E)
print('')
print(F)


tensor([[1., 2.],
        [3., 4.]])

tensor([[5., 6.],
        [7., 8.]])

tensor([[10., 12.],
        [14., 16.]])

tensor([[11., 14.],
        [17., 20.]])

tensor([[ 5., 12.],
        [21., 32.]])

tensor([[19., 22.],
        [43., 50.]])


### Floats versus integers

In [51]:
x=torch.Tensor([1.2 , 2.5])
print(x)
print(x.type())

tensor([1.2000, 2.5000])
torch.FloatTensor


In [24]:
y=torch.LongTensor([5,6])
print(y)
print(y.type())

tensor([5, 6])
torch.LongTensor


In [25]:
y=y.float()
print(y)
print(y.type())

tensor([5., 6.])
torch.FloatTensor


In [26]:
x=x.long()
print(x)
print(x.type())

tensor([1, 2])
torch.LongTensor


### Other functions

In [27]:
x=torch.arange(10)
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


In [28]:
x=torch.randperm(10)
print(x)
print(x.type())

tensor([9, 4, 7, 3, 6, 2, 0, 5, 1, 8])
torch.LongTensor


In [29]:
x=torch.arange(10).long()
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


### Tips

Check tensor sizes for algebra computations like multiplication torch.mm(X1,X2) with X1.size(), X2.size()

Check tensor type for data manipulations with X.type()

### Reshaping a tensor

In [30]:
x=torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [31]:
print( x.view(2,5) )

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [32]:
print( x.view(5,2) )

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


### Note that the original tensor x was NOT modified

In [33]:
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


### To make the change permanent you need to create a new tensor

In [34]:
y=x.view(5,2)

print(x)
print('')
print(y)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


### Slicing a tensor

In [35]:
print( y )

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [36]:
print( y[0] )

tensor([0, 1])


In [37]:
print( y[1] )

tensor([2, 3])


In [38]:
v = y[2]
print(v)

tensor([4, 5])


### Extract row 1 (included) to row 4 (excluded)

In [39]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [40]:
print( y[1:4] )

tensor([[2, 3],
        [4, 5],
        [6, 7]])


In [41]:
idx = 1
n=3

print( y[idx:idx+n] )

tensor([[2, 3],
        [4, 5],
        [6, 7]])


### Let check the sizes after slicing

In [42]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [43]:
z= y[1:1+3]
print(z)

print('')

print('dimension=',z.dim())
print(z.size())

tensor([[2, 3],
        [4, 5],
        [6, 7]])

dimension= 2
torch.Size([3, 2])


In [44]:
v=y[1]
print(v)

print('')


print('dimension=',v.dim())
print(v.size())

tensor([2, 3])

dimension= 1
torch.Size([2])


### Acessing the entries of a Tensor

In [45]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [46]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [47]:
a=y[4,0]
print(a) # a is a scalar, not a tensor

tensor(8)


In [48]:
print(a.dim())
print(a.size())

0
torch.Size([])


### A matrix is 2-dimensional Tensor
### A row of a matrix is a 1-dimensional Tensor
### An entry of a matrix is a 0-dimensional  Tensor

### 0-dimensional Tensor are scalar!

### If we want to convert a 0-dimensional Tensor into  python number, we need to use item()

In [49]:
b=a.item()
print(a)
print(type(a))
print(b)
print(type(b))

tensor(8)
<class 'torch.Tensor'>
8
<class 'int'>
