# Lab 03 : Vanilla neural networks -- exercise

# Creating a one-layer network

In [2]:
import torch
import torch.nn as nn

### Make a class for a one layer network. Let's call the layer "mylayer". And let's give it a bias.

In [7]:
class one_layer_net(nn.Module):

    def __init__(self,  input_size, output_size  ):
        super(one_layer_net , self).__init__()
        self.mylayer=nn.Linear(input_size,output_size,bias=True)
        
        # complete here
        
        
    def forward(self, x):
        x=self.mylayer(x)
        p=torch.softmax(x,dim=0)
        # complete here
        # complete here
        
        return p

### Create an instance of a one layer net that take input of size 2 and return output of size 2

In [8]:
net=one_layer_net(input_size=2,output_size=2) # complete here
print(net)

one_layer_net(
  (mylayer): Linear(in_features=2, out_features=2, bias=True)
)


### Make a vector $x=\begin{bmatrix}1\\1 \end{bmatrix}$ and feed it to the network. What is the output probability? Check that it sums to one.

In [9]:
x=torch.Tensor([1,1]) # complete here
print(x)

p = net(x)  # complete here
print(p)

print(p.sum() )

tensor([1., 1.])
tensor([0.8359, 0.1641], grad_fn=<SoftmaxBackward0>)
tensor(1., grad_fn=<SumBackward0>)


### Print the weights as well as the bias of the unique layer of this network. Be careful to use the correct name for this unique layer 

In [18]:
print(net.mylayer.weight) # complete here)
print(net.mylayer.bias) # complete here)
print(list(net.parameters()))

Parameter containing:
tensor([[ 0.0541,  0.2577],
        [-0.3128, -0.3864]], requires_grad=True)
Parameter containing:
tensor([ 0.3638, -0.2530], requires_grad=True)
[Parameter containing:
tensor([[ 0.0541,  0.2577],
        [-0.3128, -0.3864]], requires_grad=True), Parameter containing:
tensor([ 0.3638, -0.2530], requires_grad=True)]


### Change the internal parameters of your network so that the weights are now equal to 
$
W=\begin{bmatrix}
1&2 \\ 3&4 
\end{bmatrix}
$ and the bias is equal to  $
b=\begin{bmatrix}
1 \\ 1 
\end{bmatrix}
$ 

In [20]:
with torch.no_grad():
    # CHANGE THE WEIGHTS
    net.mylayer.weight[0][0]=1
    net.mylayer.weight[0][1]=2
    net.mylayer.weight[1][0]=3
    net.mylayer.weight[1][1]=4

    # CHANGE THE BIAS
    net.mylayer.bias[0]=1
    net.mylayer.bias[1]=1

    print(net.mylayer.weight)
    print(net.mylayer.bias)

Parameter containing:
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
Parameter containing:
tensor([1., 1.], requires_grad=True)


### Feed the vector x to your network with updated parameters. What is the output? (you should get p= [2% 98%])

In [22]:
p=net(x) # complete here
print(p)

tensor([0.0180, 0.9820], grad_fn=<SoftmaxBackward0>)
